# Generated by Django 5.0.14 on 2026-08-26 13:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handle', models.SlugField(unique=True)),
                ('niche', models.CharField(blank=True, default='', max_length=80)),
                ('platforms', models.JSONField(blank=True, default=dict)),
                ('audience_size', models.PositiveIntegerField(default=0)),
                ('is_eligible', models.BooleanField(default=False)),
                ('eligibility_checked_at', models.DateTimeField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('stats_updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=140)),
                ('media_url', models.URLField(blank=True, default='')),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='creators.creatorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
