# Generated by Django 5.0.14 on 2026-08-26 10:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('tier', models.CharField(choices=[('STYLE', 'Style'), ('DISCOVER', 'Discover'), ('AI_DESIGNER', 'AI Personal Designer')], max_length=20)),
                ('price_inr', models.PositiveIntegerField()),
                ('billing_interval_days', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('ai_text_daily_limit', models.PositiveIntegerField(default=5)),
                ('ai_image_monthly_limit', models.PositiveIntegerField(default=3)),
                ('max_saved_looks', models.PositiveIntegerField(default=20)),
                ('wardrobe_item_limit', models.PositiveIntegerField(default=0)),
                ('designer_chat_enabled', models.BooleanField(default=False)),
                ('customization_requests_enabled', models.BooleanField(default=False)),
                ('features', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['tier', 'price_inr'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('TRIALING', 'Trialing'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past due'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired')], default='TRIALING', max_length=12)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('provider', models.CharField(blank=True, default='', max_length=30)),
                ('provider_subscription_id', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='subscriptions.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='subscriptio_user_id_28ce5e_idx')],
            },
        ),
    ]
