# Generated by Django 5.0.14 on 2026-08-26 13:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pitch', models.TextField(blank=True, default='', max_length=1500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=12)),
                ('performance', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=140)),
                ('brief', models.TextField(max_length=3000)),
                ('deliverables', models.JSONField(blank=True, default=list)),
                ('budget_inr', models.PositiveIntegerField()),
                ('payout_inr', models.PositiveIntegerField(blank=True, null=True)),
                ('min_audience', models.PositiveIntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Accepting applications'), ('CLOSED', 'Closed for applications'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=12)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
