# Generated by Django 5.0.14 on 2026-08-26 13:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('icon', models.CharField(default='✦', max_length=8)),
                ('criteria', models.JSONField(default=dict)),
                ('xp_bonus', models.PositiveIntegerField(default=25)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('occasion_slug', models.CharField(blank=True, default='', max_length=40)),
                ('hashtag', models.CharField(blank=True, default='', max_length=60)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('xp_reward', models.PositiveIntegerField(default=100)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('LIVE', 'Live'), ('CLOSED', 'Closed')], default='LIVE', max_length=12)),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='FashionXPTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(choices=[('post_created', 'Published a post'), ('item_added', 'Wardrobe item added'), ('outfit_saved', 'Saved a look'), ('designer_turn', 'AI designer session'), ('like_received', 'Post liked'), ('comment_written', 'Commented'), ('follow_received', 'Gained a follower'), ('challenge_completed', 'Challenge completed'), ('badge_unlocked', 'Badge unlocked'), ('reward_redemption', 'Reward redeemed'), ('admin_adjustment', 'Admin adjustment')], max_length=32)),
                ('ref_type', models.CharField(blank=True, default='', max_length=40)),
                ('ref_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('balance_after', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_xp', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending fulfilment'), ('GRANTED', 'Granted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=12)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('cost_xp', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField(blank=True, null=True)),
                ('partner', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField(default=0)),
                ('qualified', models.BooleanField(default=False)),
                ('ranked_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='fashionxp.challenge')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
