# Generated by Django 5.0.14 on 2026-08-26 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fashionxp', '0001_initial'),
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeentry',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='social.post'),
        ),
        migrations.AddField(
            model_name='challengeentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fashionxptransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='redemption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_redemptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='redemption',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='fashionxp.reward'),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holders', to='fashionxp.badge'),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='challengeentry',
            constraint=models.UniqueConstraint(fields=('challenge', 'user'), name='uniq_challenge_entry'),
        ),
        migrations.AddIndex(
            model_name='fashionxptransaction',
            index=models.Index(fields=['user', '-created_at'], name='fashionxp_f_user_id_f5a42d_idx'),
        ),
        migrations.AddIndex(
            model_name='fashionxptransaction',
            index=models.Index(fields=['user', 'reason', '-created_at'], name='fashionxp_f_user_id_6261c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='userbadge',
            constraint=models.UniqueConstraint(fields=('user', 'badge'), name='uniq_user_badge'),
        ),
    ]
