# Generated by Django 5.0.14 on 2026-08-26 10:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.CharField(choices=[('stylist_analysis', 'Stylist photo analysis'), ('stylist_recommend', 'Outfit recommendation'), ('designer_chat', 'Conversational designer'), ('outfit_image', 'Outfit image generation')], max_length=32)),
                ('provider', models.CharField(max_length=40)),
                ('model', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CACHED', 'Served from cache'), ('REJECTED_SAFETY', 'Rejected by safety filter')], default='SUCCESS', max_length=20)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('cache_hit', models.BooleanField(default=False)),
                ('request_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('error', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_aiusagel_user_id_679c78_idx'), models.Index(fields=['feature', '-created_at'], name='ai_aiusagel_feature_c981db_idx'), models.Index(fields=['user', 'feature', '-created_at'], name='ai_aiusagel_user_id_15a12c_idx')],
            },
        ),
    ]
