# Generated by Django 5.0.14 on 2026-08-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusagelog',
            name='feature',
            field=models.CharField(choices=[('stylist_analysis', 'Stylist photo analysis'), ('stylist_recommend', 'Outfit recommendation'), ('designer_chat', 'Conversational designer'), ('outfit_image', 'Outfit image generation'), ('wardrobe_extract', 'Wardrobe attribute extraction')], max_length=32),
        ),
    ]
