# Generated by Django 5.0.14 on 2026-08-26 13:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('designers', '0001_initial'),
        ('fashion', '0003_alter_generatedoutfit_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('western', 'Western'), ('ethnic', 'Ethnic & Traditional'), ('fusion', 'Fusion'), ('footwear', 'Footwear'), ('accessories', 'Accessories'), ('custom', 'Made-to-Measure')], max_length=16)),
                ('price_inr', models.PositiveIntegerField()),
                ('sale_price_inr', models.PositiveIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=80)),
                ('fabric', models.CharField(blank=True, default='', max_length=60)),
                ('colors', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_customizable', models.BooleanField(default=False)),
                ('ready_to_ship', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=80)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='brands.brandprofile')),
                ('designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='designers.designerprofile')),
                ('seller_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(max_length=500, upload_to='products/')),
                ('alt', models.CharField(blank=True, default='', max_length=160)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.product')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=60)),
                ('price_delta_inr', models.IntegerField(default=0)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='marketplace.product')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brief', models.TextField(max_length=2000)),
                ('budget_inr', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('RESPONDED', 'Responded'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined by customer'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=12)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to=settings.AUTH_USER_MODEL)),
                ('design_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fashion.generatedoutfit')),
                ('designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='designers.designerprofile')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='marketplace.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_inr', models.PositiveIntegerField()),
                ('timeline_days', models.PositiveSmallIntegerField(default=14)),
                ('notes', models.TextField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('SUPERSEDED', 'Superseded')], default='PROPOSED', max_length=12)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='marketplace.quoterequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', '-created_at'], name='marketplace_is_acti_39fb3f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='marketplace_categor_e01614_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['city'], name='marketplace_city_0d3459_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'name', 'value'), name='uniq_variant'),
        ),
        migrations.AddIndex(
            model_name='quoterequest',
            index=models.Index(fields=['customer', '-created_at'], name='marketplace_custome_b6c568_idx'),
        ),
    ]
