# Generated by Django 5.0.14 on 2026-08-26 10:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, default='')),
                ('formality', models.PositiveSmallIntegerField(default=3)),
                ('palette_bias', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['formality', 'label'],
            },
        ),
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='New design', max_length=120)),
                ('design_state', models.JSONField(blank=True, default=dict)),
                ('occasion', models.CharField(blank=True, default='', max_length=40)),
                ('budget_inr', models.PositiveIntegerField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designer_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant'), ('SYSTEM', 'System')], max_length=12)),
                ('content', models.TextField()),
                ('changes', models.JSONField(blank=True, default=list)),
                ('design_version', models.PositiveIntegerField(blank=True, null=True)),
                ('image_job_id', models.UUIDField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='fashion.aiconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedOutfit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('STYLIST', 'AI Stylist'), ('DESIGNER', 'AI Designer'), ('CUSTOMIZE', 'Customize This Look')], max_length=12)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', max_length=12)),
                ('title', models.CharField(blank=True, default='', max_length=140)),
                ('occasion', models.CharField(blank=True, default='', max_length=40)),
                ('budget_inr', models.PositiveIntegerField(blank=True, null=True)),
                ('recommendation', models.JSONField(blank=True, default=dict)),
                ('design_state', models.JSONField(blank=True, default=dict)),
                ('image_prompt', models.TextField(blank=True, default='')),
                ('image', models.URLField(blank=True, default='')),
                ('version', models.PositiveIntegerField(default=1)),
                ('saved', models.BooleanField(default=False)),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('failed_reason', models.CharField(blank=True, default='', max_length=255)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outfits', to='fashion.aiconversation')),
                ('source_outfit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customized_versions', to='fashion.generatedoutfit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['user', '-updated_at'], name='fashion_aic_user_id_a2b80d_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedoutfit',
            index=models.Index(fields=['user', '-created_at'], name='fashion_gen_user_id_710014_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedoutfit',
            index=models.Index(fields=['user', 'saved', '-saved_at'], name='fashion_gen_user_id_f12971_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedoutfit',
            index=models.Index(fields=['source', '-created_at'], name='fashion_gen_source_7763bf_idx'),
        ),
    ]
