# Generated by Django 5.0.14 on 2026-08-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedoutfit',
            name='image',
            field=models.ImageField(blank=True, default='', max_length=500, upload_to='outfits/'),
        ),
    ]
