# Generated by Django 5.0.14 on 2026-08-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0002_alter_generatedoutfit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedoutfit',
            name='source',
            field=models.CharField(choices=[('STYLIST', 'AI Stylist'), ('DESIGNER', 'AI Designer'), ('CUSTOMIZE', 'Customize This Look'), ('WARDROBE', 'From My Closet')], max_length=12),
        ),
    ]
