# Generated by Django 5.0.14 on 2026-08-26 10:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_styles', models.JSONField(blank=True, default=list)),
                ('favorite_colors', models.JSONField(blank=True, default=list)),
                ('avoided_colors', models.JSONField(blank=True, default=list)),
                ('fit_preference', models.CharField(blank=True, choices=[('SLIM', 'Slim'), ('REGULAR', 'Regular'), ('RELAXED', 'Relaxed'), ('MIXED', 'Depends on outfit')], default='', max_length=12)),
                ('budget_min', models.PositiveIntegerField(blank=True, null=True)),
                ('budget_max', models.PositiveIntegerField(blank=True, null=True)),
                ('clothing_preferences', models.JSONField(blank=True, default=dict)),
                ('common_occasions', models.JSONField(blank=True, default=list)),
                ('traditional_modern_balance', models.PositiveSmallIntegerField(default=50, help_text='0 = fully modern, 100 = fully traditional')),
                ('completion_cache', models.PositiveSmallIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='style_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=60)),
                ('bio', models.TextField(blank=True, default='', max_length=500)),
                ('city', models.CharField(blank=True, default='', max_length=80)),
                ('gender', models.CharField(blank=True, choices=[('WOMAN', 'Woman'), ('MAN', 'Man'), ('NON_BINARY', 'Non-binary'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], default='', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
