# Generated by Django 5.0.14 on 2026-08-26 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WardrobeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='Untitled piece', max_length=120)),
                ('category', models.CharField(choices=[('tops', 'Tops'), ('bottoms', 'Bottoms'), ('dresses', 'Dresses'), ('outerwear', 'Outerwear'), ('footwear', 'Footwear'), ('accessories', 'Accessories'), ('ethnic', 'Ethnic & Traditional'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting analysis'), ('READY', 'Ready'), ('FAILED', 'Analysis failed')], default='PENDING', max_length=12)),
                ('image', models.ImageField(blank=True, default='', max_length=500, upload_to='wardrobe/')),
                ('color_primary', models.CharField(blank=True, default='', max_length=40)),
                ('color_hex', models.CharField(blank=True, default='', max_length=9)),
                ('fabric', models.CharField(blank=True, default='', max_length=60)),
                ('pattern', models.CharField(blank=True, default='', max_length=60)),
                ('formality', models.PositiveSmallIntegerField(default=3)),
                ('seasons', models.JSONField(blank=True, default=list)),
                ('occasion_slugs', models.JSONField(blank=True, default=list)),
                ('style_tags', models.JSONField(blank=True, default=list)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('notes', models.CharField(blank=True, default='', max_length=300)),
                ('favorite', models.BooleanField(default=False)),
                ('times_worn', models.PositiveIntegerField(default=0)),
                ('last_worn_at', models.DateTimeField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='wardrobe_wa_user_id_b13d4e_idx'), models.Index(fields=['user', 'category'], name='wardrobe_wa_user_id_0741de_idx')],
            },
        ),
    ]
